version: '2'

services:
  
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - ecommerce-red
    restart: always  

networks:
  ecommerce-red:
    driver: bridge
